"""Add user authentication and profile fields

Revision ID: 174d8055ab95
Revises: 4607d1cf9799
Create Date: 2025-12-04 00:26:44.405851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '174d8055ab95'
down_revision: Union[str, Sequence[str], None] = '4607d1cf9799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add password_hash as nullable first
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))

    # Set default password hash for existing users (they'll need to reset password)
    op.execute("UPDATE users SET password_hash = '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5GyVy/ubku3Z.' WHERE password_hash IS NULL")

    # Now make it not nullable
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               nullable=False)

    op.add_column('users', sa.Column('software_background', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('hardware_background', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('learning_goals', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('experience_level', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('personalization_enabled', sa.Boolean(), server_default='true', nullable=True))
    op.add_column('users', sa.Column('preferred_language', sa.String(length=10), server_default='en', nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))

    # Update email column - set dummy email for users without one
    op.execute("UPDATE users SET email = username || '@example.com' WHERE email IS NULL")

    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'preferred_language')
    op.drop_column('users', 'personalization_enabled')
    op.drop_column('users', 'experience_level')
    op.drop_column('users', 'learning_goals')
    op.drop_column('users', 'hardware_background')
    op.drop_column('users', 'software_background')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
